variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest

    steps:
    - checkout: self
      clean: true
      fetchTags: true
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(BuildParameters.RestoreBuildProjects)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*[Tt]est*/*.csproj'
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: Downloading code from Staging Artifact
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: Deploying to 3DTSL API Dev
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'OrthoPediatrics Playbook(2b4140e4-6c1a-403c-ac26-f0d4d9a91a58)'
        appType: 'webApp'
        WebAppName: '3dtslapidev'
        packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'
        ExcludeFilesFromAppDataFlag: false
        AdditionalArguments: 
